### ISSUE TITLE
Missing Tree Items and Broken Navigation

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#122]
After upgrading from beta 30 to 33, no "leaf" nodes are shown in the navigation sidebar. When expanding any menu (ie. Tables), only a single entry called "Tree Item" is listed. Furthermore, when clicking on any branch header (ie. public schema), phpPgAdmin attempts to display the "template1" database, which contains no objects. Navigation using the sidebar tree is not usable in its present state.

**Comment by amenadiel** [comment]
@klaxian thanks for noticing. Apparently I kept the fix in my dev branch. Now I've released it as beta 34. Please update.

**Comment by klaxian** [comment]
Thanks for working on this, but I'm still having problems. After pulling origin/master, the normal frameset now appears nearly blank. There is a 500 server error when loading `src/views/intro.php`. However, there is nothing in my logs. Enabling `display_errors` also does not output anything. Perhaps some PHP code is sending the 500 response code directly? It appears to fail somewhere in `IntroController`.

Should I be pulling from a different branch instead of master? On a related note, I'm still seeing some comments with "beta.33" in code. Am I missing something? Thanks.
